version: '3.8'

services:
  web:
    build: ./onsiteiq
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./onsiteiq/:/usr/src/onsiteiq/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=onsiteiq
      - POSTGRES_PASSWORD=onsiteiq
      - POSTGRES_DB=onsiteiq

volumes:
  postgres_data: